DROP TABLE IF EXISTS DIAS_CONSULTA;
DROP TABLE IF EXISTS AGENDAS;

CREATE TABLE AGENDAS (
	ID SERIAL PRIMARY KEY,
	ID_PROFESIONAL INTEGER REFERENCES PROFESIONALES(ID_PROFESIONAL) NOT NULL,
	FECHA_DESDE DATE NOT NULL,
	FECHA_HASTA DATE NOT NULL
);

INSERT INTO AGENDAS(ID_PROFESIONAL, FECHA_DESDE, FECHA_HASTA)
VALUES(2, CURRENT_DATE, CURRENT_DATE + 10);

INSERT INTO AGENDAS(ID_PROFESIONAL, FECHA_DESDE, FECHA_HASTA)
VALUES(7, CURRENT_DATE, CURRENT_DATE + 20);

DROP TABLE IF EXISTS DIAS_CONSULTA;
CREATE TABLE DIAS_CONSULTA(
	ID SERIAL PRIMARY KEY,
	ID_AGENDA INTEGER REFERENCES AGENDAS(ID) NOT NULL,
	ID_DIA INTEGER REFERENCES DIAS(ID) NOT NULL,
	ID_ESPECIALIDAD INTEGER REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD) NOT NULL,
	ID_TURNO INTEGER REFERENCES TURNOS(ID) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL
);

INSERT INTO DIAS_CONSULTA(ID_AGENDA, ID_DIA, ID_ESPECIALIDAD, ID_TURNO, HORA_INICIO, HORA_FIN)
VALUES(1, 1, 1, 1, '08:00', '11:00');  --LUNES, MAÑANA DE 8 A 11

INSERT INTO DIAS_CONSULTA(ID_AGENDA, ID_DIA, ID_ESPECIALIDAD, ID_TURNO, HORA_INICIO, HORA_FIN)
VALUES(1, 1, 1, 2, '13:00', '15:00'); --LUNES, TARDE DE 13 A 15

INSERT INTO DIAS_CONSULTA(ID_AGENDA, ID_DIA, ID_ESPECIALIDAD, ID_TURNO, HORA_INICIO, HORA_FIN)
VALUES(2, 4, 3, 2, '13:00', '17:00'); --JUEVES, TARDE DE 13 A 17

DROP TABLE IF EXISTS ESTADOS_CITA;

CREATE TABLE ESTADOS_CITA(
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL
);

INSERT INTO ESTADOS_CITA (DESCRIPCION)
VALUES('EN CURSO');

INSERT INTO ESTADOS_CITA (DESCRIPCION)
VALUES('CANCELADO PACIENTE');

INSERT INTO ESTADOS_CITA (DESCRIPCION)
VALUES('CANCELADO PROFESIONAL');

INSERT INTO ESTADOS_CITA (DESCRIPCION)
VALUES('ASISTIO');

INSERT INTO ESTADOS_CITA (DESCRIPCION)
VALUES('NO ASISTIO');

SELECT * FROM ESTADOS_CITA;

DROP TABLE IF EXISTS CITAS;
CREATE TABLE CITAS(
	ID_CITA SERIAL PRIMARY KEY,
	ID_PACIENTE INTEGER REFERENCES PACIENTES(ID_PACIENTE) NOT NULL,
	ID_PROFESIONAL INTEGER REFERENCES PROFESIONALES(ID_PROFESIONAL) NOT NULL,
	ESTADO INTEGER REFERENCES ESTADOS_CITA(ID) DEFAULT 1 NOT NULL,
	ID_TURNO INTEGER REFERENCES TURNOS(ID) NOT NULL,
	ID_ESPECIALIDAD INTEGER REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD) NOT NULL,
	FECHA DATE NOT NULL,
	HORA TIME NOT NULL
);

ALTER TABLE CITAS  
ADD COLUMN FECHA_RESERVA TIMESTAMP;

ALTER TABLE CITAS ALTER COLUMN FECHA_RESERVA SET DEFAULT CURRENT_TIMESTAMP;

/*VISTA*/
CREATE OR REPLACE VIEW LISTA_FECHAS_DISPONIBLES AS 
SELECT
	B.ID AS ID_AGENDA,
	B.ID_PROFESIONAL,
	INITCAP(F.PRIMER_NOMBRE || ' ' || COALESCE(F.SEGUNDO_NOMBRE, '') || ' ' || COALESCE(F.TERCER_NOMBRE, '')  || ' ' || F.PRIMER_APELLIDO || ' ' || COALESCE(F.SEGUNDO_APELLIDO, '')) PROFESIONAL,
	B.FECHA_DESDE,
	B.FECHA_HASTA,
	A.ID AS ID_DIA_CONSULTA,
	A.ID_DIA,
	A.ID_ESPECIALIDAD,
	C.DESCRIPCION AS ESPECIALIDAD,
	A.ID_TURNO,
	D.DESCRIPCION AS TURNO,
	A.HORA_INICIO,
	A.HORA_FIN
FROM DIAS_CONSULTA A
INNER JOIN AGENDAS B ON B.ID = A.ID_AGENDA
INNER JOIN ESPECIALIDADES C ON C.ID_ESPECIALIDAD = A.ID_ESPECIALIDAD
INNER JOIN TURNOS D ON D.ID = A.ID_TURNO
INNER JOIN PROFESIONALES E ON E.ID_PROFESIONAL = B.ID_PROFESIONAL
LEFT JOIN PERSONAS F ON F.ID_PERSONA = E.ID_PERSONA
ORDER BY B.ID, A.ID_DIA, A.HORA_INICIO;

SELECT *
FROM LISTA_FECHAS_DISPONIBLES
WHERE 7 = 7 ;
SELECT * FROM ESPECIALIDADES