DROP TABLE IF EXISTS FERIADOS;

CREATE TABLE FERIADOS (
	ID SERIAL PRIMARY KEY,
	DIA smallint NOT NULL,
	MES smallint NOT NULL,
	ANHO smallint NOT NULL,
	MOTIVO VARCHAR(200) NOT NULL
);

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(1,1,2023, 'Año Nuevo');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(27,2,2023, 'Día de los Héroes');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(6,4,2023, 'Jueves Santo');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(7,4,2023, 'Viernes Santo');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(1,5,2023, 'Día de los Trabajadores');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(14,5,2023, 'Día de la Independencia');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(15,5,2023, 'Día de la Independencia');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(12,6,2023, 'Día de la Paz del Chaco');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(15,8,2023, 'Día de la fundación de Asunción');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(29,9,2023, 'Victoria de Boquerón');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(8,12,2023, 'Día de la Virgen de Caacupé');

INSERT INTO FERIADOS(DIA, MES, ANHO, MOTIVO)
VALUES(25,12,2023, 'Navidad');

SELECT * FROM FERIADOS;