DROP TABLE IF EXISTS ESPECIALIDADES;

CREATE TABLE ESPECIALIDADES (
	ID_ESPECIALIDAD SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL --(A) Activo, (I) Inactivo
);