DROP TABLE IF EXISTS ESPECIALIDADES;

CREATE TABLE ESPECIALIDADES (
	ID_ESPECIALIDAD SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL, --(A) Activo, (I) Inactivo
	PRECIO NUMERIC NOT NULL
);

INSERT INTO ESPECIALIDADES (DESCRIPCION, PRECIO)
VALUES('Tratamiento individual', 120000);

INSERT INTO ESPECIALIDADES (DESCRIPCION, PRECIO)
VALUES('Tratamiento para la Ansiedad', 120000);

INSERT INTO ESPECIALIDADES (DESCRIPCION, PRECIO)
VALUES('Tratamiento para la Depresión', 120000);

INSERT INTO ESPECIALIDADES (DESCRIPCION, PRECIO)
VALUES('Desarrollo Personal y Autoestima', 120000);

INSERT INTO ESPECIALIDADES (DESCRIPCION, PRECIO)
VALUES('Recuperación post evento', 120000);

DROP TABLE IF EXISTS CONSULTAS;

CREATE TABLE CONSULTAS (
	ID_CONSULTA SERIAL PRIMARY KEY,
	ID_PACIENTE INTEGER NOT NULL REFERENCES PACIENTES(ID_PACIENTE),
	ID_PROFESIONAL INTEGER NOT NULL REFERENCES PROFESIONALES(ID_PROFESIONAL),
	ID_ESPECIALIDAD INTEGER NOT NULL REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD),
	FECHA_CONSULTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MOTIVO VARCHAR(2000),
	ANTECEDENTE VARCHAR(2000),
	DIAGNOSTICO_ACTUAL VARCHAR(2000),
	TECNICA_APLICADA VARCHAR(2000));