DROP TABLE IF EXISTS TURNOS;
DROP TABLE IF EXISTS DIAS;

CREATE TABLE TURNOS (
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL
);

INSERT INTO TURNOS(DESCRIPCION)
VALUES('Mañana');

INSERT INTO TURNOS(DESCRIPCION)
VALUES('Tarde');

CREATE TABLE DIAS(
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL
);

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(0, 'Domingo');

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(1, 'Lunes');

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(2, 'Martes');

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(3, 'Miércoles');

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(4, 'Jueves');

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(5, 'Viernes');

INSERT INTO DIAS(ID, DESCRIPCION)
VALUES(6, 'Sábado');

SELECT * FROM DIAS;

CREATE TABLE TIPOS_DOCUMENTO (
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL
);

INSERT INTO TIPOS_DOCUMENTO(DESCRIPCION)
VALUES ('CI');

INSERT INTO TIPOS_DOCUMENTO(DESCRIPCION)
VALUES ('RUC');

INSERT INTO TIPOS_DOCUMENTO(DESCRIPCION)
VALUES ('Pasaporte');

INSERT INTO TIPOS_DOCUMENTO(DESCRIPCION)
VALUES ('Carnet de residente permanente');

INSERT INTO TIPOS_DOCUMENTO(DESCRIPCION)
VALUES ('Carnet de residente temporario');

INSERT INTO TIPOS_DOCUMENTO(DESCRIPCION)
VALUES ('Otros');

SELECT * FROM TIPOS_DOCUMENTO;

