/*SELECT
	CASE GENERO
		WHEN 'M' THEN 'MASCULINO'
		WHEN 'F' THEN 'FEMENINO'
		ELSE 'OTROS'
	END AS GENERO,
	COUNT(*) AS CANTIDAD
FROM PACIENTES A
INNER JOIN PERSONAS B ON B.ID_PERSONA = A.ID_PERSONA
GROUP BY GENERO;
*/


/*
WITH TEMP1 AS (
	SELECT
		*, CAST(EXTRACT (YEAR FROM AGE(CURRENT_DATE, B.FECHA_NACIMIENTO)) AS INTEGER) AS EDAD
	FROM PACIENTES A
	INNER JOIN PERSONAS B ON B.ID_PERSONA = A.ID_PERSONA
),

TEMP2 AS (
	SELECT *, 
		CASE
		WHEN EDAD <= 17 THEN 'MENORES'
		WHEN EDAD > 17 AND EDAD < 65 THEN 'ADULTOS'
		ELSE 'ADULTOS MAYORES'
	END AS CATEG_EDAD
	FROM TEMP1
)

SELECT 
	CATEG_EDAD,
	COUNT(*) AS CANTIDAD
FROM TEMP2
GROUP BY CATEG_EDAD;
*/

/*
WITH TEMP1 AS (
	SELECT A.*, B.*,
		CASE
			WHEN A.ESTADO = 1 THEN 'AUSENTES'
			WHEN A.ESTADO IN (2,3) THEN 'CANCELADOS'
			WHEN A.ESTADO = 4 THEN 'ASISTIDAS'
			ELSE 'OTROS'
		END AS CATEG_CITAS
	FROM CITAS A
	INNER JOIN ESTADOS_CITA B ON B.ID = A.ESTADO
	WHERE FECHA < CURRENT_DATE
)

SELECT 
	CATEG_CITAS,
	COUNT(*) AS CANTIDAD
FROM TEMP1
--WHERE EXTRACT(MONTH FROM FECHA) = 5 AND EXTRACT(YEAR FROM FECHA) = 2023
GROUP BY CATEG_CITAS
UNION
SELECT 'PENDIENTES' AS categ_citas, COUNT(*) 
FROM CITAS
WHERE FECHA >= CURRENT_DATE AND ESTADO = 1 AND COD_FACTURA IS NULL --AND EXTRACT(MONTH FROM FECHA) = 5 AND EXTRACT(YEAR FROM FECHA) = 2023
*/

/*
SELECT 
	CASE
		WHEN COD_FACTURA IS NULL THEN 'PENDIENTES'
		ELSE 'FINALIZADAS'
	END AS TIPO,
	COUNT(*)
FROM CITAS
WHERE ESTADO = 4 AND EXTRACT(MONTH FROM FECHA) = 5 AND EXTRACT(YEAR FROM FECHA) = 2023
GROUP BY TIPO
UNION
SELECT 'EN CURSO' AS TIPO, COUNT(*) AS CANTIDAD 
FROM SALA_ESPERA
WHERE ID_ESTADO = 2

--ESPECIALIDADES

SELECT 
	B.DESCRIPCION AS NAME,
	COUNT(A.*) AS VALUE
FROM CONSULTAS A
INNER JOIN ESPECIALIDADES B ON B.ID_ESPECIALIDAD = A.ID_ESPECIALIDAD
GROUP BY B.DESCRIPCION*/

SELECT 
	B.DESCRIPCION AS NAME,
	COUNT(A.*) AS VALUE
FROM CONSULTAS A
INNER JOIN MOTIVOS_CONSULTA B ON B.ID = A.COD_MOTIVO
GROUP BY B.DESCRIPCION
