/*

SELECT 
	SUM(A.MONTO) AS MONTO,
	B.DESCRIPCION AS TIPO,
	EXTRACT(MONTH FROM A.FECHA_CREACION) AS MES,
	EXTRACT(YEAR FROM A.FECHA_CREACION) AS ANHO
FROM MOVIMIENTOS A
INNER JOIN TIPO_MOVIMIENTO B ON B.ID = A.TIPO
WHERE A.ESTADO = 'V'
GROUP BY TIPO, MES, ANHO, B.DESCRIPCION

*/

--MIRADA DIARIA


SELECT 
	SUM(A.MONTO) AS MONTO,
	B.DESCRIPCION AS TIPO,
	EXTRACT(DAY FROM A.FECHA_CREACION) AS DIA,
	EXTRACT(MONTH FROM A.FECHA_CREACION) AS MES,
	EXTRACT(YEAR FROM A.FECHA_CREACION) AS ANHO
FROM MOVIMIENTOS A
INNER JOIN TIPO_MOVIMIENTO B ON B.ID = A.TIPO
WHERE A.ESTADO = 'V' AND A.TIPO = 1
GROUP BY TIPO, MES, ANHO, DIA, B.DESCRIPCION
ORDER BY DIA, MES, ANHO