DROP VIEW IF EXISTS VIEW_USUARIOS;

CREATE OR REPLACE VIEW VIEW_USUARIOS AS 
	WITH PACIENTES AS (
		SELECT PE.TIPO_DOC, PE.NRO_DOC, US.ID, US.EMAIL, US.STATUS, 'PACIENTE'::text AS TIPO, 3 AS ID_TIPO_ROL
		FROM PACIENTES PA
		INNER JOIN PERSONAS PE ON PE.ID_PERSONA = PA.ID_PERSONA
		INNER JOIN USERS US ON US.ID = PA.ID_USUARIO
	), 

	PROFESIONALES AS (
		SELECT PE.TIPO_DOC, PE.NRO_DOC, US.ID, US.EMAIL, US.STATUS, 'PROFESIONALES'::text AS TIPO, 2 AS ID_TIPO_ROL
		FROM PROFESIONALES PA
		INNER JOIN PERSONAS PE ON PE.ID_PERSONA = PA.ID_PERSONA
		INNER JOIN USERS US ON US.ID = PA.ID_USUARIO
	),

	ADMINS AS (
		SELECT PE.TIPO_DOC, PE.NRO_DOC, US.ID, US.EMAIL, US.STATUS, 'ADMINS'::text AS TIPO, 1 AS ID_TIPO_ROL
		FROM ADMINISTRADORES PA
		INNER JOIN PERSONAS PE ON PE.ID_PERSONA = PA.ID_PERSONA
		INNER JOIN USERS US ON US.ID = PA.ID_USUARIO
	),

	UNIONS AS (
		SELECT * FROM PACIENTES
		UNION
		SELECT * FROM PROFESIONALES
		UNION
		SELECT * FROM ADMINS
	)

	SELECT * FROM UNIONS ORDER BY ID;

SELECT * FROM VIEW_USUARIOS
WHERE TIPO_DOC = 1 AND NRO_DOC = '5549070'


SELECT * FROM USERS WHERE ID = 1