
DROP FUNCTION IF EXISTS REGISTRAR_CONSULTA (CONSULTAS.ID_PACIENTE%TYPE,
											CONSULTAS.ID_PROFESIONAL%TYPE,
										   	CONSULTAS.ID_ESPECIALIDAD%TYPE,
											CONSULTAS.MOTIVO%TYPE,
											CONSULTAS.ANTECEDENTE%TYPE,
										   	CONSULTAS.DIAGNOSTICO_ACTUAL%TYPE,
										    CONSULTAS.TECNICA_APLICADA%TYPE,
										    INTEGER,
										    INTEGER);
	
CREATE OR REPLACE FUNCTION REGISTRAR_CONSULTA (
	--DATOS DE LA CONSULTA
	ID_PAC CONSULTAS.ID_PACIENTE%TYPE,
	ID_PRO CONSULTAS.ID_PROFESIONAL%TYPE,
	ID_ESP CONSULTAS.ID_ESPECIALIDAD%TYPE,
	MOT CONSULTAS.MOTIVO%TYPE,
	ANT CONSULTAS.ANTECEDENTE%TYPE,
	DIA CONSULTAS.DIAGNOSTICO_ACTUAL%TYPE,
	TEC CONSULTAS.TECNICA_APLICADA%TYPE,
	IDM INTEGER,
	IDD INTEGER
)
RETURNS RESPUESTA
LANGUAGE plpgsql
AS $$
DECLARE 
	RESP RESPUESTA%ROWTYPE;
BEGIN
	INSERT INTO CONSULTAS(ID_PACIENTE, ID_PROFESIONAL, ID_ESPECIALIDAD, MOTIVO, ANTECEDENTE, DIAGNOSTICO_ACTUAL, TECNICA_APLICADA, COD_MOTIVO, COD_DIAGNOSTICO)
	VALUES(ID_PAC, ID_PRO, ID_ESP, MOT, ANT, DIA, TEC, IDM, IDD);
	
    --CONSULTA REGISTRADA!
	RESP.ID := 0;
	RESP.MSG := '¡Consulta registrada correctamente!';
	
	RETURN RESP;

EXCEPTION	
	WHEN OTHERS THEN
		RESP.ID := 1;
		RESP.MSG := SQLERRM;
		RETURN RESP;
END;
$$;

SELECT * FROM CONSULTAS ORDER BY ID_CONSULTA;