DROP TABLE IF EXISTS MOTIVOS_CONSULTA;
DROP TABLE IF EXISTS DIAGNOSTICOS_CONSULTA;

CREATE TABLE MOTIVOS_CONSULTA (
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL
);

INSERT INTO MOTIVOS_CONSULTA(DESCRIPCION) VALUES ('Motivo 1');
INSERT INTO MOTIVOS_CONSULTA(DESCRIPCION) VALUES ('Motivo 2');
INSERT INTO MOTIVOS_CONSULTA(DESCRIPCION) VALUES ('Motivo 3');

CREATE TABLE DIAGNOSTICOS_CONSULTA (
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL
);

INSERT INTO DIAGNOSTICOS_CONSULTA(DESCRIPCION) VALUES ('Diagnostico 1');
INSERT INTO DIAGNOSTICOS_CONSULTA(DESCRIPCION) VALUES ('Diagnostico 2');
INSERT INTO DIAGNOSTICOS_CONSULTA(DESCRIPCION) VALUES ('Diagnostico 3');

SELECT * FROM MOTIVOS_CONSULTA


ALTER TABLE CONSULTAS ADD COD_MOTIVO INTEGER REFERENCES MOTIVOS_CONSULTA(ID);
ALTER TABLE CONSULTAS ADD COD_DIAGNOSTICO INTEGER REFERENCES DIAGNOSTICOS_CONSULTA(ID);

UPDATE CONSULTAS SET COD_MOTIVO = 4, COD_DIAGNOSTICO = 4

SELECT * FROM CONSULTAS;