
CREATE OR REPLACE FUNCTION GET_CANTIDAD_PACIENTES (
	ID INTEGER, --id_profesional 
	DESDE DATE,
	HASTA DATE
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE 
	CANTIDAD INTEGER;
BEGIN
	SELECT COUNT(*) AS CANTIDAD INTO CANTIDAD 
	FROM CITAS
	WHERE ID_PROFESIONAL = ID AND FECHA BETWEEN DESDE AND HASTA;
	
	RETURN COALESCE(CANTIDAD, 0);
END;
$$;

SELECT GET_CANTIDAD_PACIENTES (11, '2023-05-30', '2023-06-07')