
CREATE OR REPLACE FUNCTION GET_CANTIDAD_PACIENTES (
	ID INTEGER, --id_profesional 
	DESDE DATE,
	HASTA DATE
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE 
	CANTIDAD INTEGER;
BEGIN
	SELECT COUNT(*) AS CANTIDAD INTO CANTIDAD 
	FROM CITAS
	WHERE ID_PROFESIONAL = ID AND ESTADO = 1 AND FECHA BETWEEN DESDE AND HASTA;
	
	RETURN COALESCE(CANTIDAD, 0);
END;
$$;

SELECT GET_CANTIDAD_PACIENTES (11, '2023-05-30', '2023-06-07')


select * from citas where estado = 1 order by id_cita

SELECT * FROM CITAS
WHERE ID_PROFESIONAL = 11 AND /*ESTADO = 1 AND*/ FECHA = CURRENT_DATE


select * from estados_cita


SELECT * FROM AGENDAS
SELECT * FROM DIAS_CONSULTA


	SELECT *
	FROM CITAS
	WHERE ID_PROFESIONAL = 11 AND ESTADO = 1 AND FECHA BETWEEN '2023-05-30' AND '2023-06-07';