
/*ELIMINAR*/
DROP FUNCTION IF EXISTS ELIMINAR_PROFESIONAL(PROFESIONALES.ID_PROFESIONAL%TYPE);

CREATE OR REPLACE FUNCTION ELIMINAR_PROFESIONAL (
	ID_PRO PROFESIONALES.ID_PROFESIONAL%TYPE
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
	ID_USER USERS.ID%TYPE;
	ESTADO USERS.STATUS%TYPE;
BEGIN
	SELECT ID_USUARIO INTO ID_USER
	FROM PROFESIONALES
	WHERE ID_PROFESIONAL = ID_PRO;
	
	SELECT STATUS INTO ESTADO
	FROM USERS
	WHERE ID = ID_USER;
		
	UPDATE USERS
	SET STATUS = 'B', FECHA_BAJA = CURRENT_TIMESTAMP
	WHERE ID = ID_USER;
END;
$$;

SELECT ELIMINAR_PROFESIONAL(1);
