
DROP VIEW IF EXISTS AGENDAS_PROFESIONALES;
CREATE OR REPLACE VIEW AGENDAS_PROFESIONALES AS
SELECT 
	A.ID,
	A.ID_PROFESIONAL,
	A.FECHA_HASTA AS ORDEN,
	TO_CHAR(A.FECHA_DESDE, 'dd/mm/yyyy') AS FECHA_DESDE,
	TO_CHAR(A.FECHA_HASTA, 'dd/mm/yyyy') AS FECHA_HASTA,
	INITCAP(PE.PRIMER_NOMBRE || ' ' || COALESCE(PE.SEGUNDO_NOMBRE, '') || ' ' || COALESCE(PE.TERCER_NOMBRE, '')  || ' ' || PE.PRIMER_APELLIDO || ' ' || COALESCE(PE.SEGUNDO_APELLIDO, '')) AS NAME,
	CASE
		WHEN A.FECHA_HASTA <= NOW() THEN 'VENCIDO'
		WHEN EXTRACT(DAYS FROM A.FECHA_HASTA::TIMESTAMP - NOW()) <= 15 THEN 'POR VENCER'
		ELSE 'VIGENTE'
	END AS ESTADO
FROM AGENDAS A
LEFT JOIN PROFESIONALES P ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
LEFT JOIN PERSONAS PE ON PE.ID_PERSONA = P.ID_PERSONA;



SELECT * FROM AGENDAS_PROFESIONALES WHERE ID_PROFESIONAL = 2;