
DROP VIEW IF EXISTS AGENDAS_PROFESIONALES;
CREATE OR REPLACE VIEW AGENDAS_PROFESIONALES AS
SELECT A.*, 
	REPLACE(INITCAP(PE.PRIMER_NOMBRE || ' ' || COALESCE(PE.SEGUNDO_NOMBRE, '') || ' ' || COALESCE(PE.TERCER_NOMBRE, '')  || ' ' || PE.PRIMER_APELLIDO || ' ' || COALESCE(PE.SEGUNDO_APELLIDO, '')), '  ', '') AS NAME,
	CASE
		WHEN A.FECHA_HASTA <= NOW() THEN 'VENCIDO'
		WHEN A.FECHA_HASTA > CURRENT_DATE AND A.FECHA_HASTA <= CURRENT_DATE - 20 THEN 'POR VENCER'
		ELSE 'EN CURSO'
	END AS ESTADO
FROM AGENDAS A
LEFT JOIN PROFESIONALES P ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
LEFT JOIN PERSONAS PE ON PE.ID_PERSONA = P.ID_PERSONA;