DROP VIEW IF EXISTS LISTA_PROFESIONALES;

CREATE OR REPLACE VIEW LISTA_PROFESIONALES AS
	SELECT 
		A.ID_PROFESIONAL AS ID,
		INITCAP(B.PRIMER_NOMBRE || ' ' || COALESCE(B.SEGUNDO_NOMBRE, '') || ' ' || COALESCE(B.TERCER_NOMBRE, '')  || ' ' || B.PRIMER_APELLIDO || ' ' || COALESCE(B.SEGUNDO_APELLIDO, '')) AS NAME,
		B.NRO_DOC,
		A.REGISTRO,
		D.DESCRIPCION AS TIPO_DOC,
		CAST (EXTRACT (YEAR FROM AGE(CURRENT_DATE, B.FECHA_NACIMIENTO)) AS INTEGER) AS EDAD,
		CASE UPPER(GENERO)
			WHEN 'M' THEN 'Masculino'
			WHEN 'F' THEN 'Femenino'
			WHEN 'P' THEN 'Prefiero no decirlo'
			ELSE
				'Otro'
		END AS GENERO,
		C.EMAIL,
		C.TELEFONO,
		CASE C.STATUS
			WHEN 'A' THEN 'Activa'
			WHEN 'B' THEN 'Baja'
			WHEN 'I' THEN 'Inactiva'
			ELSE
				'Desconocido'
		END AS STATUS,
		F.DESCRIPCION || ' - ' || E.DESCRIPCION AS RESIDENCIA
	FROM PROFESIONALES A
	INNER JOIN PERSONAS B ON B.ID_PERSONA = A.ID_PERSONA
	INNER JOIN USERS C ON C.ID = A.ID_USUARIO
	INNER JOIN TIPOS_DOCUMENTO D ON D.ID = B.TIPO_DOC
	INNER JOIN CIUDADES E ON E.COD_CONCATENADO = B.LUGAR_RESIDENCIA
	INNER JOIN DEPARTAMENTOS F ON F.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
	WHERE C.ROLE = 2 AND C.STATUS <> 'B';

SELECT * FROM LISTA_PROFESIONALES;

