DROP FUNCTION IF EXISTS OBTENER_SALDO();

CREATE OR REPLACE FUNCTION OBTENER_SALDO ()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE 
	SALDO INTEGER;
BEGIN
	WITH INGRESO AS (
		SELECT 
			1 AS COD, SUM(MONTO) AS INGRESO
		FROM MOVIMIENTOS
		WHERE ESTADO = 'V' AND TIPO = 1
	),

	EGRESO AS (
		SELECT 
			1 AS COD, SUM(MONTO) AS EGRESO
		FROM MOVIMIENTOS
		WHERE ESTADO = 'V' AND TIPO = 2
	)

	SELECT COALESCE(B.INGRESO, 0) -  COALESCE(A.EGRESO, 0) AS SALDO INTO SALDO
	FROM EGRESO A
	INNER JOIN INGRESO B ON B.COD = A.COD;
	
	RETURN SALDO;
	
END;
$$;

SELECT OBTENER_SALDO();

