DROP TABLE IF EXISTS MOVIMIENTOS;
DROP TABLE IF EXISTS CATEGORIA_MOVIMIENTO;
DROP TABLE IF EXISTS TIPO_MOVIMIENTO;

CREATE TABLE TIPO_MOVIMIENTO(
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(20) NOT NULL
);

INSERT INTO TIPO_MOVIMIENTO(DESCRIPCION) VALUES ('Ingreso');
INSERT INTO TIPO_MOVIMIENTO(DESCRIPCION) VALUES ('Egreso');

CREATE TABLE CATEGORIA_MOVIMIENTO(
	ID SERIAL PRIMARY KEY,
	ID_TIPO INTEGER REFERENCES TIPO_MOVIMIENTO(ID) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL
);

--CATEGORIAS INGRESOS
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Consultas', 1);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Apertura de caja', 1);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Otros (Justificar)', 1);

--CATEGORIAS EGRESOS
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Pago salarios', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Alquiler', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Gastos administrativos', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Pago a proveedores', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Servicios básicos (Energía/Agua potable)', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Internet', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Seguros', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Mantenimientos', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Impuestos', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Prestamos', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Compras patrimonio', 2);
INSERT INTO CATEGORIA_MOVIMIENTO(DESCRIPCION, ID_TIPO) VALUES ('Otros (Justificar)', 2);


CREATE TABLE MOVIMIENTOS (
	ID SERIAL PRIMARY KEY,
	MONTO INTEGER NOT NULL,
	TIPO INTEGER REFERENCES TIPO_MOVIMIENTO(ID) NOT NULL,
	MEDIO_PAGO VARCHAR(2) DEFAULT 'EF' NOT NULL, --EF: EFECTIVO
	CATEGORIA INTEGER REFERENCES CATEGORIA_MOVIMIENTO(ID) NOT NULL,
	NRO_FACTURA VARCHAR(20) NULL,
	COMENTARIO VARCHAR(150) NULL,
	ESTADO VARCHAR(1) DEFAULT 'V' NULL,
	COD_FACTURA INTEGER REFERENCES FACTURAS_VENTA(COD_FACTURA),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

SELECT * FROM MOVIMIENTOS;
SELECT * FROM TIPO_MOVIMIENTO;
SELECT * FROM CATEGORIA_MOVIMIENTO;


SELECT
	M.ID,
	M.FECHA_CREACION AS FECHA,
	TM.DESCRIPCION AS TIPO,
	M.TIPO,
	CASE UPPER(MEDIO_PAGO)
		WHEN 'EF' THEN 'Efectivo'
		ELSE 'Otro'
	END AS FORMA,
	CM.DESCRIPCION AS CONCEPTO,
	M.MONTO AS IMPORTE,
	M.NRO_FACTURA,
	M.COMENTARIO
FROM MOVIMIENTOS M
INNER JOIN TIPO_MOVIMIENTO TM ON TM.ID = M.TIPO
INNER JOIN CATEGORIA_MOVIMIENTO CM ON CM.ID = M.CATEGORIA;