DROP FUNCTION IF EXISTS AGREGAR_ITEM_FACTURA(
	FACTURAS_VENTA.COD_FACTURA%TYPE,
	ESPECIALIDADES.ID_ESPECIALIDAD%TYPE,
	INTEGER
); 

CREATE OR REPLACE FUNCTION AGREGAR_ITEM_FACTURA(
	ID_FACTURA FACTURAS_VENTA.COD_FACTURA%TYPE,
	ID_ITEM ESPECIALIDADES.ID_ESPECIALIDAD%TYPE,
	CANT INTEGER
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO DETALLES_FACTURA(COD_FACTURA, ID_ITEM, CANTIDAD)
	VALUES (ID_FACTURA, ID_ITEM, CANT);
	
	RETURN 1; --TODO OK!!
	
EXCEPTION
	WHEN OTHERS THEN
		RETURN 0; --ERROR!!!
END;
$$;

SELECT AGREGAR_ITEM_FACTURA(1, 1, 1);