
DROP TABLE IF EXISTS CLIENTE_FACTURA;

CREATE TABLE CLIENTE_FACTURA (
	ID SERIAL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(100) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(100) NULL,
	TERCER_NOMBRE VARCHAR(100) NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	NRO_DOC VARCHAR(50) NOT NULL,
	TIPO_DOC INTEGER REFERENCES TIPOS_DOCUMENTO(ID) NOT NULL,
	DIRECCION VARCHAR(200) NOT NULL
);

ALTER TABLE CLIENTE_FACTURA ADD CIUDAD INTEGER REFERENCES CIUDADES(COD_CONCATENADO);
ALTER TABLE CLIENTE_FACTURA ADD EMAIL VARCHAR(100);

SELECT * FROM CLIENTE_FACTURA;