DROP VIEW IF EXISTS DATOS_FACTURA_DETALLE;
CREATE OR REPLACE VIEW DATOS_FACTURA_DETALLE AS (
	SELECT 
	A.COD_FACTURA,
	A.ID_ITEM,
	B.DESCRIPCION,
	A.CANTIDAD,
	B.PRECIO,
	A.CANTIDAD * B.PRECIO AS TOTAL
	FROM DETALLES_FACTURA A
	INNER JOIN ESPECIALIDADES B ON B.ID_ESPECIALIDAD = A.ID_ITEM
	ORDER BY A.COD_FACTURA, A.ID_ITEM
);

SELECT * FROM DATOS_FACTURA_DETALLE;