DROP FUNCTION IF EXISTS EMITIR_FACTURA(
	FACTURAS_VENTA.COD_FACTURA%TYPE,
	VARCHAR(20)
);

CREATE OR REPLACE FUNCTION EMITIR_FACTURA(
	ID_FACTURA FACTURAS_VENTA.COD_FACTURA%TYPE,
	CODIGO VARCHAR(20)
)
RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE
	TOTAL_IVA NUMERIC;
	GRAVADO NUMERIC;
	TOTAL_FAC NUMERIC;
	NRO_FAC VARCHAR(20);
	COD_CITA_FAC INTEGER;
	FEC_EMIS TIMESTAMP;
BEGIN
	--CALCULO IVA
	SELECT 
		SUM(CASE B.PORC_IVA
				WHEN 10 THEN (A.CANTIDAD * B.PRECIO) / 11
				WHEN 5 THEN (A.CANTIDAD * B.PRECIO) / 21
			ELSE 0
		END) AS IVA INTO TOTAL_IVA
	FROM DETALLES_FACTURA A
	INNER JOIN ESPECIALIDADES B ON B.ID_ESPECIALIDAD = A.ID_ITEM
	WHERE A.COD_FACTURA = ID_FACTURA;
	
	--CALCULO TOTAL FACTURA
	SELECT SUM(A.CANTIDAD * B.PRECIO) AS TOTAL INTO TOTAL_FAC
	FROM DETALLES_FACTURA A
	INNER JOIN ESPECIALIDADES B ON B.ID_ESPECIALIDAD = A.ID_ITEM
	WHERE A.APLICAR_COBRO = 'S' AND A.COD_FACTURA = ID_FACTURA;
	
	--CALCULO GRABADA
	SELECT 
		SUM(CASE B.PORC_IVA
				WHEN 10 THEN (A.CANTIDAD * B.PRECIO) - ((A.CANTIDAD * B.PRECIO) / 11)
				WHEN 5 THEN (A.CANTIDAD * B.PRECIO) - ((A.CANTIDAD * B.PRECIO) / 21)
				ELSE (A.CANTIDAD * B.PRECIO)
			END) AS IVA INTO GRAVADO
	FROM DETALLES_FACTURA A
	INNER JOIN ESPECIALIDADES B ON B.ID_ESPECIALIDAD = A.ID_ITEM
	WHERE A.COD_FACTURA = ID_FACTURA;
	
	--OBTENER NÚMERO DE FACTURA
	SELECT NUMERO_FACTURA INTO NRO_FAC
	FROM FACTURAS_VENTA
	WHERE COD_FACTURA = ID_FACTURA;

	--ACTUALIZACION DEL REGISTRO
	UPDATE FACTURAS_VENTA
	SET MONTO_GRAVADO = ROUND(GRAVADO, 2),
		MONTO_IVA = ROUND(TOTAL_IVA, 2),
		TOTAL = TOTAL_FAC,
		ESTADO = 'V',
		ID_FACTURA_PDF = CODIGO
	WHERE COD_FACTURA = ID_FACTURA;
	
	--ACTUALIZAR TABLA CITAS
	SELECT CODIGO_CITA, FECHA_EMISION INTO COD_CITA_FAC, FEC_EMIS
	FROM FACTURAS_VENTA
	WHERE COD_FACTURA = ID_FACTURA;
	
	UPDATE CITAS
	SET COD_FACTURA = ID_FACTURA
	WHERE ID_CITA = COD_CITA_FAC;
	
	--TABLA DETALLES
	INSERT INTO DETALLES_PAGO(COD_FACTURA, FORMA_PAGO, MONTO)
	VALUES(ID_FACTURA, 'EF', TOTAL_FAC);

	--TABLA MOVIMIENTO
	INSERT INTO MOVIMIENTOS (MONTO, TIPO, CATEGORIA, NRO_FACTURA, COD_FACTURA, FECHA_CREACION)
	VALUES(TOTAL_FAC, 1, 1, NRO_FAC, ID_FACTURA, FEC_EMIS);

	RETURN NRO_FAC; --TODO OK!!
	
EXCEPTION
	WHEN OTHERS THEN
		RETURN NULL; --ERROR!!!
END;
$$;

--SELECT EMITIR_FACTURA(1, 'lAHma7ppYPxgCU6SrZ17');
--SELECT * FROM FACTURAS_VENTA;
--SELECT * FROM  DETALLES_FACTURA;