DROP TABLE IF EXISTS TIMBRADOS;
DROP TABLE IF EXISTS CONTRIBUYENTES;

CREATE TABLE CONTRIBUYENTES (
	ID SERIAL PRIMARY KEY,
	RAZON_SOCIAL VARCHAR(200) NOT NULL,
	ALIAS VARCHAR(200) NOT NULL,
	TIPO_PERSONA VARCHAR(2) NOT NULL, --PF: Persona Física, PJ: Persona Jurídica,
	RUC VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(500) NOT NULL,
	UBICACION INTEGER REFERENCES CIUDADES(COD_CONCATENADO) NOT NULL,
	TELEFONO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	ACTIVIDAD VARCHAR(200) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL --A: Activo, B: Baja
);

CREATE TABLE TIMBRADOS (
	ID SERIAL PRIMARY KEY,
	CONTRIBUYENTE INTEGER REFERENCES CONTRIBUYENTES(ID) NOT NULL,
	NRO_TIMBRADO NUMERIC(8) NOT NULL,
	ESTABLECIMINETO NUMERIC(3) NOT NULL,
	EXPEDICION NUMERIC(3) NOT NULL,
	NRO_DESDE INTEGER NOT NULL,
	NRO_HASTA INTEGER NOT NULL,
	FECHA_DESDE DATE NOT NULL,
	FECHA_HASTA DATE NOT NULL,
	ULT_NRO_EMITIDO INTEGER DEFAULT 0 NOT NULL,
	TIPO_DOC VARCHAR(1) DEFAULT 'F' NOT NULL, --F: Factura
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL --A: Activo, B: Baja
);

SELECT DISTINCT ID, RUC FROM CONTRIBUYENTES;