
SELECT * FROM FACTURAS_VENTA WHERE COD_FACTURA = 73  --45000
SELECT * FROM DETALLES_PAGO WHERE COD_FACTURA = 73;

DELETE FROM MOVIMIENTOS
WHERE COD_FACTURA = 72;

DELETE FROM DETALLES_PAGO
WHERE COD_FACTURA = 72;

--PARA EFECTIVO
INSERT INTO DETALLES_PAGO(COD_FACTURA, FORMA_PAGO, MONTO)
VALUES(72, 'EF', 120000);

--PARA TARJETAS
INSERT INTO DETALLES_PAGO(COD_FACTURA, FORMA_PAGO, MONTO, MARCA_TARJETA, NUMERO_TARJETA, COD_REFERENCIA)
VALUES(72, 'TC', 100000, 'Visa', '7840', '65656569');

INSERT INTO DETALLES_PAGO(COD_FACTURA, FORMA_PAGO, MONTO, MARCA_TARJETA, NUMERO_TARJETA, COD_REFERENCIA)
VALUES(72, 'TD', 150000, 'American Express', '0001', '98974215');

--PARA TRANSFERENCIAS
INSERT INTO DETALLES_PAGO(COD_FACTURA, FORMA_PAGO, MONTO, MARCA_TARJETA, NRO_CUENTA, COD_REFERENCIA)
VALUES(72, 'TR', 60000, 'Financiera', '5656265', '4454455');

--PARA BILLETERIAS
INSERT INTO DETALLES_PAGO(COD_FACTURA, FORMA_PAGO, MONTO, MARCA_TARJETA, NRO_TELEFONO, COD_REFERENCIA)
VALUES(72, 'BI', 20000, 'Zimple', '0971165540', '98562450');

/*FUNCION MOV*/
DROP FUNCTION IF EXISTS REGISTRAR_MOVIMIENTO(INTEGER);
CREATE OR REPLACE FUNCTION REGISTRAR_MOVIMIENTO(
	ID_FACTURA FACTURAS_VENTA.COD_FACTURA%TYPE
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE 
	SUMA_EF INTEGER;
	SUMA_OT INTEGER;
	FEC TIMESTAMP;
	NUMERO VARCHAR(20);
BEGIN
	SELECT SUM(MONTO) INTO SUMA_EF
	FROM DETALLES_PAGO
	WHERE FORMA_PAGO = 'EF' AND COD_FACTURA = ID_FACTURA;
	
	SELECT SUM(MONTO) INTO SUMA_OT
	FROM DETALLES_PAGO
	WHERE FORMA_PAGO <> 'EF' AND COD_FACTURA = ID_FACTURA;
	
	SELECT FECHA_EMISION, NUMERO_FACTURA INTO FEC, NUMERO
	FROM FACTURAS_VENTA
	WHERE COD_FACTURA = ID_FACTURA;
	
	IF (SUMA_EF IS NOT NULL) THEN
		INSERT INTO MOVIMIENTOS (MONTO, TIPO, MEDIO_PAGO, CATEGORIA, NRO_FACTURA, COD_FACTURA, FECHA_CREACION)
		VALUES(SUMA_EF, 1, 'EF', 1, NUMERO, ID_FACTURA, FEC);
	END IF;
	
	IF (SUMA_OT IS NOT NULL) THEN 
		INSERT INTO MOVIMIENTOS (MONTO, TIPO, MEDIO_PAGO, CATEGORIA, NRO_FACTURA, COD_FACTURA, FECHA_CREACION)
		VALUES(SUMA_OT, 1, 'CU', 1, NUMERO, ID_FACTURA, FEC);
	END IF;
	
	RETURN 0; --TODO OK!!
	
EXCEPTION
	WHEN OTHERS THEN
		RETURN 1; --ERROR!!!
END;
$$;

SELECT * FROM FACTURAS_VENTA WHERE NUMERO_FACTURA ='001-001-0000080'
SELECT * FROM DETALLES_PAGO WHERE COD_FACTURA = 76
