CREATE OR REPLACE FUNCTION CHECK_CITA (ID_PRO INTEGER,
									   FEC_CITA TIMESTAMP)
RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE 
	ID_CIT INTEGER;
	RESP VARCHAR(15);
BEGIN
	SELECT ID_CITA INTO ID_CIT 
	FROM CITAS
	WHERE ID_PROFESIONAL = ID_PRO AND (FECHA + HORA) = FEC_CITA AND ESTADO = 1;
	
	IF ID_CIT IS NULL THEN
		RETURN 'LIBRE';
	ELSE
		RETURN 'RESERVADO';
	END IF;
END; $$

--SELECT * FROM CITAS;
SELECT CHECK_CITA(2, '2023-03-27 08:10:00')