DROP VIEW IF EXISTS DIAS_CONSULTA_PROFESIONAL;
CREATE OR REPLACE VIEW DIAS_CONSULTA_PROFESIONAL AS
WITH TURNO_M AS (
	SELECT * FROM DIAS_CONSULTA
	WHERE ID_TURNO = 1
),

TURNO_T AS (
	SELECT * FROM DIAS_CONSULTA
	WHERE ID_TURNO = 2
),

IDS AS (
	SELECT DISTINCT ID_AGENDA, ID_DIA
	FROM DIAS_CONSULTA
)

SELECT 
	A.*, 
	D.DESCRIPCION AS DIA,
	E.ID_PROFESIONAL,
	F.DESCRIPCION AS ESPECIALIDAD,
	COALESCE(TO_CHAR(B.HORA_INICIO, 'HH24:MI') || ' a ' || TO_CHAR(B.HORA_FIN, 'HH24:MI'), 'No aplica') AS TURNO_MAN, 
	COALESCE(TO_CHAR(C.HORA_INICIO, 'HH24:MI') || ' a ' || TO_CHAR(C.HORA_FIN, 'HH24:MI'), 'No aplica') AS TURNO_TAR
FROM IDS A
LEFT JOIN TURNO_M B ON B.ID_AGENDA = A.ID_AGENDA AND B.ID_DIA = A.ID_DIA
LEFT JOIN TURNO_T C ON C.ID_AGENDA = A.ID_AGENDA AND C.ID_DIA = A.ID_DIA
LEFT JOIN DIAS D ON D.ID = COALESCE(B.ID_DIA,C.ID_DIA)
LEFT JOIN AGENDAS E ON E.ID = A.ID_AGENDA
LEFT JOIN ESPECIALIDADES F ON F.ID_ESPECIALIDAD = COALESCE(B.ID_ESPECIALIDAD,C.ID_ESPECIALIDAD)
ORDER BY COALESCE(B.ID_DIA,C.ID_DIA);


--SELECT * FROM DIAS_CONSULTA_PROFESIONAL WHERE ID_AGENDA = 22;