DROP VIEW IF EXISTS LISTA_ATENCION_CURSO;
CREATE OR REPLACE VIEW LISTA_ATENCION_CURSO AS (
	WITH CANT AS (
	SELECT 
		ID_PACIENTE, 
		COUNT(*) AS CANT
	FROM CONSULTAS
	GROUP BY ID_PACIENTE
	)

	SELECT
		A.ID_CITA,
		B.ID_PACIENTE,
		B.ID_PROFESIONAL,
		C.ID_ESPECIALIDAD AS ID_ESP_CITA,
		C.DESCRIPCION AS ESPECIALIDAD,
		D.DESCRIPCION AS TURNO,
		TO_CHAR(B.HORA, 'HH24:MI') AS HORARIO,
		INITCAP(F.PRIMER_NOMBRE || ' ' || COALESCE(F.SEGUNDO_NOMBRE, '') || ' ' || COALESCE(F.TERCER_NOMBRE, '')  || ' ' || F.PRIMER_APELLIDO || ' ' || COALESCE(F.SEGUNDO_APELLIDO, '')) AS NOMBRE_PACIENTE,
		'(' || G.DESCRIPCION || ') ' || F.NRO_DOC AS DOC,
		COALESCE(H.CANT, 0) AS CANT_SES
	FROM SALA_ESPERA A
	INNER JOIN CITAS B ON B.ID_CITA = A.ID_CITA
	INNER JOIN ESPECIALIDADES C ON C.ID_ESPECIALIDAD = B.ID_ESPECIALIDAD
	INNER JOIN TURNOS D ON D.ID = B.ID_TURNO
	INNER JOIN PACIENTES E ON E.ID_PACIENTE = B.ID_PACIENTE
	INNER JOIN PERSONAS F ON F.ID_PERSONA = E.ID_PERSONA
	INNER JOIN TIPOS_DOCUMENTO G ON G.ID = F.TIPO_DOC
	LEFT JOIN CANT H ON H.ID_PACIENTE = B.ID_PACIENTE
	WHERE B.FECHA = CURRENT_DATE AND A.ID_ESTADO = 2 
	LIMIT 1
);