DROP VIEW IF EXISTS LISTA_EN_CONSULTORIO;
CREATE OR REPLACE VIEW LISTA_EN_CONSULTORIO AS (
WITH CANT AS (
SELECT 
	ID_PACIENTE, 
	COUNT(*) AS CANT
FROM CONSULTAS
GROUP BY ID_PACIENTE
)
	
SELECT 
	ROW_NUMBER() OVER (PARTITION BY A.ID_PROFESIONAL ORDER BY A.ID_PROFESIONAL) AS ORDEN,
	A.ID_CITA,
	A.ID_PACIENTE AS NRO_EXP,
	A.ID_PROFESIONAL,
	INITCAP(C.PRIMER_NOMBRE || ' ' || C.PRIMER_APELLIDO) AS PACIENTE,
	D.DESCRIPCION AS TIPO_DOC,
	C.NRO_DOC,
	INITCAP(F.PRIMER_NOMBRE || ' ' || F.PRIMER_APELLIDO) AS PROFESIONAL,
	G.DESCRIPCION AS ESPECIALIDAD,
	TO_CHAR(A.HORA, 'HH24:MI') AS HORARIO,
	I.DESCRIPCION AS ESTADO,
	J.DESCRIPCION AS TURNO,
	COALESCE(K.CANT, 0) AS CANT_SES
FROM CITAS A
INNER JOIN PACIENTES B ON B.ID_PACIENTE = A.ID_PACIENTE
INNER JOIN PERSONAS C ON C.ID_PERSONA = B.ID_PERSONA
INNER JOIN TIPOS_DOCUMENTO D ON D.ID = C.TIPO_DOC
INNER JOIN PROFESIONALES E ON E.ID_PROFESIONAL = A.ID_PROFESIONAL
INNER JOIN PERSONAS F ON F.ID_PERSONA = E.ID_PERSONA
INNER JOIN ESPECIALIDADES G ON G.ID_ESPECIALIDAD = A.ID_ESPECIALIDAD
INNER JOIN SALA_ESPERA H ON H.ID_CITA = A.ID_CITA
INNER JOIN ESTADOS_SALA_ESPERA I ON I.ID = H.ID_ESTADO
INNER JOIN TURNOS J ON J.ID = A.ID_TURNO
LEFT JOIN CANT K ON K.ID_PACIENTE = A.ID_PACIENTE
WHERE A.ID_CITA IN (SELECT DISTINCT ID_CITA FROM SALA_ESPERA) AND A.FECHA = CURRENT_DATE
ORDER BY A.ID_PROFESIONAL, A.HORA);