
DROP FUNCTION IF EXISTS ELIMINAR_PACIENTE (USERS.USERNAME%TYPE);

CREATE OR REPLACE FUNCTION ELIMINAR_PACIENTE (
	USERNAME_PARAMETRO USERS.USERNAME%TYPE
)
RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE 
	ID_USUARIO_VAR USERS.ID%TYPE;
	ID_PERSONA_VAR PERSONAS.ID_PERSONA%TYPE;
	ID_PACIENTE_VAR PACIENTES.ID_PACIENTE%TYPE;
BEGIN
	SELECT ID INTO ID_USUARIO_VAR
	FROM USERS
	WHERE TRIM(LOWER(USERNAME)) = TRIM(LOWER(USERNAME_PARAMETRO));
	
	SELECT ID_PERSONA, ID_PACIENTE INTO ID_PERSONA_VAR, ID_PACIENTE_VAR
	FROM PACIENTES
	WHERE ID_USUARIO = ID_USUARIO_VAR;
	
	DELETE FROM PACIENTES
	WHERE ID_PACIENTE = ID_PACIENTE_VAR;
	
	DELETE FROM PERSONAS
	WHERE ID_PERSONA = ID_PERSONA_VAR;
	
	DELETE FROM USERS
	WHERE ID = ID_USUARIO_VAR;
	
	IF ID_USUARIO_VAR IS NULL THEN
		RETURN 'No existe el usuario ingresado';
	ELSE
		RETURN 'Se ha eliminado correctamente al paciente: ' || TRIM(UPPER(USERNAME_PARAMETRO));
	END IF;
	
EXCEPTION
	WHEN OTHERS THEN
		RETURN "Error inesperado";
END;
$$;

SELECT ELIMINAR_PACIENTE('  jaramillo  ');