DROP TABLE IF EXISTS PACIENTES;
DROP TABLE IF EXISTS PERSONAS;

CREATE TABLE PERSONAS (
	ID_PERSONA SERIAL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(100) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(100) NULL,
	TERCER_NOMBRE VARCHAR(100) NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	NACIONALIDAD INTEGER REFERENCES PAISES(ID_PAIS) DEFAULT 139 NOT NULL, --Por defecto Paraguay
	LUGAR_NACIMIENTO INTEGER REFERENCES CIUDADES(COD_CONCATENADO) NULL, --APLICA SOLO PARA PARAGUAYOS
	ESTADO_CIVIL VARCHAR(1) NOT NULL, --(S) Soltero (C) Casado (V) Viudo (D) Divorciado (O) Otro
	GENERO VARCHAR(1) NOT NULL,	--(M) Masculino (F) Femenino, (O) Otro
	NRO_DOC VARCHAR(50) NOT NULL
);

ALTER TABLE PERSONAS ADD COLUMN TIPO_DOC INTEGER REFERENCES TIPOS_DOCUMENTO(ID);
ALTER TABLE PERSONAS ADD COLUMN DIRECCION VARCHAR(200);
ALTER TABLE PERSONAS ADD COLUMN LUGAR_RESIDENCIA INTEGER REFERENCES CIUDADES(COD_CONCATENADO);


CREATE TABLE PACIENTES (
	ID_PACIENTE SERIAL PRIMARY KEY,
	ID_PERSONA INTEGER REFERENCES PERSONAS(ID_PERSONA),
	ID_USUARIO INTEGER REFERENCES USERS(ID),
	OCUPACION VARCHAR(100) NOT NULL
);

CREATE TABLE PROFESIONALES (
	ID_PROFESIONAL SERIAL PRIMARY KEY,
	ID_PERSONA INTEGER REFERENCES PERSONAS(ID_PERSONA),
	ID_USUARIO INTEGER REFERENCES USERS(ID),
	REGISTRO VARCHAR(100) NOT NULL  --R.P. del profesional 
);