CREATE TABLE ADMINISTRADORES (
	ID_ADMIN SERIAL PRIMARY KEY,
	ID_PERSONA INTEGER REFERENCES PERSONAS(ID_PERSONA),
	ID_USUARIO INTEGER REFERENCES USERS(ID)
);

INSERT INTO ADMINISTRADORES (ID_PERSONA, ID_USUARIO)
VALUES (8, 1);