DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES (
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(20) UNIQUE NOT NULL 
);

CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	STATUS VARCHAR(1) DEFAULT 'A' NOT NULL, --(A) Activo, (I) Inactivo, (B) Baja/Cancelado
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FECHA_BAJA TIMESTAMP NULL,
	ROLE INTEGER REFERENCES ROLES(ID)
);

-- Datos semilla
INSERT INTO ROLES(DESCRIPCION) VALUES('ADMIN');
INSERT INTO ROLES(DESCRIPCION) VALUES('PROFESIONAL');
INSERT INTO ROLES(DESCRIPCION) VALUES('PACIENTE');

-- Datos del user prueba
INSERT INTO USERS(USERNAME, EMAIL, PASSWORD, ROLE) VALUES('richard', 'richard@example.com', '$2a$10$jXKixU8WWx9SlVaAgAaaeOpJXRCXu3/N2jD125eunku.jPambYSaC', 1); --returning ID; 
--PASSWORD: HolaMundo!
--Encriptado en bcrypt (https://bcrypt-generator.com/)